[project]
name = "llms-material"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.30.1",
    "torch>=2.8.0",
    "wandb>=0.22.0",
]
